final-pjt-back/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

final-pjt-back/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.playlist_list, name='playlist_list'),
    path('<int:playlist_pk>/', views.playlist_detail, name='playlist_detail'),
    path('profileplaylist/<int:user_pk>/', views.playlist_list_profile, name='playlist_list_profile'),
]

final-pjt-back/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list_create, name='index'),
    path('search/', views.search_movie, name='search'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/like/', views.like, name='like'),
    path('<int:user_pk>/recommend/', views.recommend_with_genre, name='recommend'),
    path('<int:user_pk>/combination/<int:another_user_pk>/',views.combinatnion, name='combination'),
]

final-pjt-back/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

final-pjt-back/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Document</title>
  <style>
    button {
      margin: 1px;
    }
  </style>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand pe-3 title-font" href="{% url 'movies:index' %}">홈</a>
        <a class="navbar-brand pe-3 title-font" href="{% url 'community:index' %}">커뮤니티</a>
        <a class="navbar-brand pe-3 title-font" href="{% url 'movies:recommended' %}">추천</a>
        <div class="collapse navbar-collapse d-flex justify-content-between text-white" id="navbarSupportedContent">
          <a class="active text-decoration-none text-white" aria-current="page" href="{% url 'community:create' %}"><i class="fas fa-plus"></i></a>
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              {% comment %} {% if request.user.is_authenticated %}
                <span class="me-3 content-font">환영합니다, {{ request.user }}님!</span>
                <a href="{% url 'accounts:profile' request.user.username %}" class="active btn btn-success content-font">내 프로필</a>
                <form action="{% url 'accounts:logout' %}" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input type="submit" value="로그아웃" class="btn btn-secondary content-font">
                </form>
              {% else %}
                <span class="me-3 content-font">환영합니다, 손님!</span>
                <a class="active btn btn-primary content-font" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
                <a class="active btn btn-light content-font" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
              {% endif %} {% endcomment %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    {% block content %}
    {% endblock content %}

    
  </div>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>