final-pjt-back/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list_create, name='index'),
    path('search/', views.search_movie, name='search'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/like/', views.like, name='like'),
    path('<int:user_pk>/recommend/', views.recommend_with_genre, name='recommend'),
    path('<int:user_pk>/combination/<int:another_user_pk>/',views.combinatnion, name='combination'),
]

final-pjt-back/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

final-pjt-back/movies/models.py
from django.db import models
from django.conf import settings

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)
    # 영화 좋아요
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', null=True)

final-pjt-back/movies/forms.py
from django import forms

# Create your forms here.
class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

final-pjt-back/movies/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_safe
from django.http import JsonResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from accounts.models import User
from .models import Movie, Genre
from .serializers import MovieSerializer,LikeMovieSerializer,GenreSerializer
import json

from django.views.generic import FormView
from .forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

# Create your views here.

@api_view(['GET', 'POST'])
def movie_list_create(request):
    if request.method=='GET':
        movies=Movie.objects.all()
        serializer = MovieSerializer(movies,many=True)
        return Response(serializer.data)

def search_movie(request):
    searchWord=request.GET.get('search')
    if searchWord:
        post_list = Movie.objects.filter(
            Q(title__icontains=searchWord) | Q(overview__icontains=searchWord) | Q(genres__name__icontains=searchWord)
            ).distinct()
        serializer=MovieSerializer(post_list,many=True)
        movie_list=[]
        for movie in post_list:
            movie_list.append({
                'id': movie.pk,
                'title': movie.title,
                'popularity':movie.popularity,
                'release_date': movie.release_date,
                'vote_count':movie.vote_count,
                'vote_average': movie.vote_average,
                'overview':movie.overview,
                'genres':movie.genres,
                'poster_path': movie.poster_path,
            })
        serializer = MovieSerializer(movie_list,many=True)
        response = {
        'movies': serializer.data,
    }
    return JsonResponse(response)



@api_view(['GET', 'POST'])
def detail(request,movie_pk):
    
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method=='GET':
        serializer = MovieSerializer(movie) 
        genres=serializer.data['genres']
        likeUsers=serializer.data['like_users']
        genre_list=[]
        like_list=[]
        for i in genres:
            for j in Genre.objects.all():
                if i==j.id:
                    genre_list.append(j.name)
        for i in likeUsers:
            for j in User.objects.all():
                if i==j.id:
                    like_list.append(j.username)
        context={
            'movie':serializer.data,
            'genre':genre_list,
            'like_user':like_list
        }
        
        return Response(context)


@api_view(['PUT'])
def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'PUT':
        serializer = LikeMovieSerializer(movie,data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(like_users=request.data['like_users'])
            return Response(serializer.data)



def like_movie(user_pk):
    movies=Movie.objects.all()
    user_movie_list=[]
    for movie in movies:
        if movie.like_users.filter(pk=user_pk).exists():
            user_movie_list.append(
                {'id': movie.pk,
                'title': movie.title,
                'popularity':movie.popularity,
                'release_date': movie.release_date,
                'vote_count':movie.vote_count,
                'vote_average': movie.vote_average,
                'overview':movie.overview,
                'genres':movie.genres,
                'poster_path': movie.poster_path,})
    return user_movie_list

@api_view(['GET'])
def like(request, user_pk):
    user_movie_list=like_movie(user_pk)
    serializer = MovieSerializer(user_movie_list,many=True)
    return Response(serializer.data)


@api_view(['GET'])
def recommend_with_genre(request, user_pk):
    like_movies=like_movie(user_pk)
    like_movies_id=[]
    movies=Movie.objects.all()
    genres=Genre.objects.all()
    like_genres=set()
    for i in like_movies:
        like_movies_id.append(i['id'])
        for g in i['genres'].all():
            like_genres.add(g)
    res=[movie for movie in  movies if movie.id not in like_movies_id]
    recommend={}
    for j in res:
        recommend[j.id]=0
        for g in j.genres.all():
            for genre in like_genres:
                if g==genre:
                    recommend[j.id]+=1
    recommend_list=sorted(recommend.items(), key=lambda item: item[1],reverse=True)
    recommend_movie=[]
    for k,v in recommend_list:
        recommend_movie.append(get_object_or_404(Movie, pk=k))
    serializer=MovieSerializer(recommend_movie,many=True)
    return Response(serializer.data)

@api_view(['GET'])
def combinatnion(request, user_pk,another_user_pk):
    a_like_movies=like_movie(user_pk)
    b_like_movies=like_movie(another_user_pk)

    intersection=[]
    a_complement=a_like_movies[:]
    b_complement=b_like_movies[:]

    for i in a_like_movies:
        for j in b_like_movies:
            if i['id']==j['id']: 
                intersection.append(i)

    for i in a_like_movies:
        for j in intersection:
            if i['id']==j['id']:
                a_complement.remove(i)

    for i in b_like_movies:
        for j in intersection:
            if i['id']==j['id']:
                b_complement.remove(i)
                
    intersection_serializer=MovieSerializer(intersection,many=True)
    a_complement_serializer=MovieSerializer(a_complement,many=True)
    b_complement_serializer=MovieSerializer(b_complement,many=True)

    context={
        'intersection': intersection_serializer.data,
        'a_complement':a_complement_serializer.data,
        'b_complement':b_complement_serializer.data
    }
    return JsonResponse(context)
    pass

# @require_safe
# def recommended(request):
#     movies = Movie.objects.order_by('vote_average')
#     genres = Genre.objects.order_by('name')
#     context = {
#         "movies": movies,
#         "genres": genres,
#     }
#     return render(request, "movies/recommended.html", context)


# def recommendeddata(request):
#     genre_pk = int(request.GET.get('genre'))
#     year = request.GET.get('year')
       
#     if year == '1990년대':
#         movies = Movie.objects.filter(release_date__startswith='199')
#     elif year == '2000년대':
#         movies = Movie.objects.filter(release_date__startswith='200')
#     elif year == '2010년대':
#         movies = Movie.objects.filter(release_date__startswith='201')
#     elif year == '2020년대':
#         movies = Movie.objects.filter(release_date__startswith='20')
#     else:
#         movies = Movie.objects.filter(release_date__startswith='19')
    
#     movies_list = []
#     for movie in movies:
#         for genre in movie.genres.all():
#             if genre_pk == genre.pk:
#                 movies_list.append({
#                     'pk': movie.pk,
#                     'title': movie.title,
#                     'release_date': movie.release_date,
#                     'vote_average': movie.vote_average,
#                     'poster_path': movie.poster_path,
#                 })
        
#     response = {
#         'moviesList': movies_list,
#     }
#     return JsonResponse(response)

final-pjt-back/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}

  <h1>{{ movie.title }}</h1>
  <p>🎥
    {% for genre in movie.genres.all %}
      <span style="color: red; font-weight: bold;">{{ genre.name }}</span>
    {% endfor %}
  </p>
  <p>🧑‍🤝‍🧑 <strong>관객 수</strong> : {{ movie.popularity }}</p>
  <p>🗓️ <strong>개봉 일</strong> : {{ movie.release_date }}</p>
  <p>⭐ <strong>평 점</strong> : {{ movie.vote_average }}</p>
  {% if movie.overview %}
   <p>📝 <strong>줄거리</strong> : {{ movie.overview }}</p>
  {% endif %}
  <img src="{{ movie.poster_path }}" alt="">
  <hr>
  <a href="{% url 'movies:index' %}">[BACK]</a>
  <br><br>

{% endblock %}

final-pjt-back/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  <hr>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  {% for movie in movies %}
    <div class="col">
      <div class="card h-100">
        <img src="{{ movie.poster_path }}" alt="" style="height:80%">
        <div class="card-body">
          <h5 class="card-title text-center fw-bold"> 제목 : {{ movie.title }}</h5>
          <p class="card-text">⭐ 평점 : {{ movie.vote_average }}</p>
          <p class> </p>
          <a href="{% url 'movies:detail' movie.pk %}">상세 보기</a>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
 
{% endblock %}

final-pjt-back/movies/templates/movies/post_search.html
{% extends "base.html" %}
{% block title %}post_search.html{% endblock %}
{% block content %}
<h1>Blog Search</h1>
<br>
<form action="." method="post"> {% csrf_token %}
{{ form.as_table }}
<input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>
<br/><br/>
{% if object_list %}
{% for post in object_list %}
<h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
{{ post.modify_dt|date:"N d, Y" }}
<p>{{ post.description }}</p>
{% endfor %}
{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}
{% endblock %}

final-pjt-back/movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}
  <hr>
  <div id="searchPart">
    <h3>장르</h3>
    <div>
      {% for genre in genres %}
        <button class="genre active btn btn-primary content-font" data-genre-id="{{ genre.pk }}">{{ genre.name }}</button>
      {% endfor %}
    </div>
    <hr>
     <h3>연대</h3>
    <div>
      <button class="year active btn btn-primary content-font">1990년대 이전</button>
      <button class="year active btn btn-primary content-font">1990년대</button>
      <button class="year active btn btn-primary content-font">2000년대</button>
      <button class="year active btn btn-primary content-font">2010년대</button>
      <button class="year active btn btn-primary content-font">2020년대</button>
    </div>
    <hr>
    <button class="recom active btn btn-danger content-font">추천</button>
  </div>
  <div id="moviePart">
    <div id="movieDiv" class="row row-cols-3 row-cols-md-3 g-4">
      {% for movie in movies %}
        <div class="col">
          <div class="card h-100">
            <img src="{{ movie.poster_path }}" alt="" style="height:80%">
            <div class="card-body">
              <h5 class="card-title text-center fw-bold"> 제목 : {{ movie.title }}</h5>
              <p class="card-text">⭐ 평점 : {{ movie.vote_average }}</p>
              <a href="{% url 'movies:detail' movie.pk %}">상세 보기</a>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
  </div>

  <script>
    const btnGenre = document.querySelectorAll('.genre')
    const btnYear = document.querySelectorAll('.year')
    const btnRec = document.querySelector('.recom')
    
    let selected = {
      'genre': '',
      'year': '',
    }
    btnGenre.forEach((btn)=>{
      btn.addEventListener('click', function (event) {
        const genreId = event.target.dataset.genreId
        selected.genre = genreId
      })
    })
    btnYear.forEach((btn)=>{
      btn.addEventListener('click', function (event) {
        selected.year = btn.innerText
      })
    })

    btnRec.addEventListener('click', function (event) {
      event.preventDefault()
      console.log(selected)
      clearall()
      axios({
        method: "get",
        url: '/movies/recommendeddata/',
        params: selected,
      })
      .then((response) => {
        const movieList = response.data.moviesList
        movieList.forEach((movie) => {
          const moviePk = movie.pk
          const movieTitle = movie.title
          const movieDate = movie.release_date
          const voteAvg = movie.vote_average
          const posterPath = movie.poster_path

          const div1 = document.createElement('div')
          div1.setAttribute('class', 'col')
          const div2 = document.createElement('div')
          div2.setAttribute('class', 'card h-100')
          const img = document.createElement('img')
          img.setAttribute('src', posterPath)
          img.setAttribute('class', 'card-img-top')
          img.setAttribute('style', 'height:80%')

          const div3 = document.createElement('div')
          div3.setAttribute('class', 'card-body')
          
          const cardTitle = document.createElement('h5')
          cardTitle.setAttribute('class', 'card-title text-center fw-bold')
          cardTitle.innerText = `제목 : ${movieTitle}`
          const cardText = document.createElement('p')
          cardText.setAttribute('class', 'card-text text-center')
          cardText.innerText = `⭐ 평점 : ${voteAvg}`
          const cardLink = document.createElement('a')
          cardLink.setAttribute('href', `/movies/${moviePk}/`)
          cardLink.innerText = "상세보기"

          const parentDiv = document.querySelector('#movieDiv')
          parentDiv.appendChild(div1)
          div1.appendChild(div2)
          div2.append(img, div3)
          div3.append(cardTitle, cardText, cardLink)
        })
      })
    })

    function clearall() {
      const parent = document.querySelector('#movieDiv')
      while (parent.firstChild) {
        parent.removeChild(parent.firstChild);
      }
    }
  </script>
{% endblock %}