final-pjt-back/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

final-pjt-back/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.playlist_list, name='playlist_list'),
    path('<int:playlist_pk>/', views.playlist_detail, name='playlist_detail'),
    path('profileplaylist/<int:user_pk>/', views.playlist_list_profile, name='playlist_list_profile'),
]

final-pjt-back/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list_create, name='index'),
    path('search/', views.search_movie, name='search'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/like/', views.like, name='like'),
    path('<int:user_pk>/recommend/', views.recommend_with_genre, name='recommend'),
    path('<int:user_pk>/combination/<int:another_user_pk>/',views.combinatnion, name='combination'),
]

final-pjt-back/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

final-pjt-back/community/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

class Playlist(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='community_user')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_playlists')
    movies = models.ManyToManyField(Movie, related_name='movies_playlists')

final-pjt-back/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

final-pjt-back/community/views.py
from django.shortcuts import get_object_or_404


# 이쪽이 VUE랑 연동해서 쓸 모듈들
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes, renderer_classes
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.permissions import (
    IsAuthenticated,
    AllowAny,
    )
from movies.models import Movie
from .models import Playlist
from movies.serializers import MovieSerializer
from .serializers import (
    PlayListSerializer,
    CreatePlayListSerializer
)


@api_view(['GET', 'POST'])
def playlist_list(request):
    if request.method == 'GET':
        playlists = Playlist.objects.all()
        my_playlist = []
        for playlist in playlists:
            if playlist.user_id==request.user.id:
                my_playlist.append(playlist)
        serializer =PlayListSerializer(my_playlist, many=True)
        return Response(serializer.data)
    
    elif request.method == 'POST':
        data = request.data
        serializer = CreatePlayListSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            playlist = serializer.save(user=request.user)
            for movie_id in data['movies']:
                movie = Movie.objects.get(pk=movie_id)
                playlist.movies.add(movie)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
    

@api_view(['GET', 'DELETE', 'PUT'])
def playlist_detail(request, playlist_pk):
    playlist = get_object_or_404(Playlist, pk=playlist_pk)
    
    if request.method == 'GET':
        serializer = PlayListSerializer(playlist)
        movies = playlist.movies.all()
        movie_serializer = MovieSerializer(movies, many=True)
        context = {
            'playlist' : serializer.data,
            'movies' : movie_serializer.data
        }
        return Response(context)
    
    elif request.method == 'DELETE':
        playlist.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
    elif request.method == 'PUT':
        data = request.data
        serializer = CreatePlayListSerializer(playlist, data=data)

        if serializer.is_valid(raise_exception=True):
            playlist_serializer = serializer.save()
            origin_movies = playlist.movies.all()
            for origin_movie in origin_movies:
                pp = (origin_movie.pk)
                for _ in playlist_serializer.movies.filter():
                    playlist.movies.remove(pp)
            
            for movie_id in data['movies']:
                movie = Movie.objects.get(pk=movie_id)
                playlist.movies.add(movie)
            return Response(serializer.data)


@api_view(['GET', 'POST'])
def playlist_list_profile(request, user_pk):
    if request.method == 'GET':
        playlists = Playlist.objects.all()
        my_playlist = []
        for playlist in playlists:
            if playlist.user_id==user_pk:
                my_playlist.append(playlist)
        serializer =PlayListSerializer(my_playlist, many=True)
        return Response(serializer.data)

final-pjt-back/community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock %}

final-pjt-back/community/templates/community/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">DETAIL</h2>
  <h3>{{ review.pk }} 번째 글</h3>
  <hr>
  <p>제목: {{ review.title }}</p>
  <p>영화 제목: {{ review.movie_title }}</p>
  <p>내용: {{ review.content }}</p>
  <p>평점: {{ review.rank }}</p>
  <p>작성 시각: {{ review.created_at }}</p>
  <p>수정 시각: {{ review.updated_at }}</p>
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
      {{ comment.user }} - {{ comment.content }}
    </div>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock  %}

final-pjt-back/community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Community</h1>
  <a href="{% url 'community:create' %}">[create]</a>
  <hr>
  {% for review in reviews %}
    <p>작성자 : <a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></p>
    <p>글 번호: {{ review.pk }}</p>
    <p>글 제목: {{ review.title }}</p>
    <p>글 내용: {{ review.content }}</p>
    <form class="like-forms" data-review-id="{{ review.pk }}">
      {% csrf_token %}
      {% if request.user in review.like_users.all %}
        <button id="like-{{ review.pk }}">좋아요 취소</button>
      {% else %}
        <button id="like-{{ review.pk }}">좋아요</button>
      {% endif %}
    </form>
    <p>
      <span id="review-count">{{ review.like_users.all|length }}</span> 명이 이 글을 좋아합니다.
    </p>
    <a href="{% url 'community:detail' review.pk %}">[detail]</a>
    <hr>

  {% endfor %}
  

  <script>
    const forms = document.querySelectorAll('.like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    const reviewCount = document.querySelector('#review-count')

    forms.forEach((form) => {
      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const reviewId = event.target.dataset.reviewId
        
        axios({
          method: 'post',
          url: `/community/${reviewId}/like/`,
          headers: {'X-CSRFToken': csrftoken},
        })
        .then((response) => {
          const isLiked = response.data.is_liked
          const likeCount = response.data.like_count
          const likeBtn = document.querySelector(`#like-${reviewId}`)
          reviewCount.innerText = likeCount
          if (isLiked === true) {
            likeBtn.innerText = '좋아요 취소'
          } else {
            likeBtn.innerText = '좋아요'
          }    
        })
        .catch((error) => {
          console.log(error.response)
        })
      })
    })
  </script>

{% endblock %}